# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:US4nbVZgSdd6zDlQM5wVm2R+Y4XRwcQAdQ==,iv:s+Rea7CSbNUYYtZx4RT3HvuTkVyxCt7pldLe29PZeUc=,tag:c7K3SMaT22nvCkWJdgydog==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:VWOjosLUK73qUS6A5/1SfnsSVEod+rrpHabvO7a7sRAJhCHswQ==,iv:xh4ijW4+xdLiHQseiQLRQEoqEMGLUVijaTpwLz54JP4=,tag:MJwAQc606DeTTzkC0xr+hg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:vme0e4lGA4zHFRCsuHXIXo9g0g==,iv:Kht2Zg0OowYJpC0mzSL3l9f028HdQS+BJvtKwpRIJLU=,tag:r4MKXN5o1GL5JatUQ3mL8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zcvg7j382g4lsdaq46lhapjg5eg6guuf4vx9ce0zy2p7qngzqd6spqnmgp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbzNaMEIvaUtSYlJRaS9v
            UE1NS2orOVJpbXRBTVNCV1FmSmNwa29laXo0CmphdlU1NjNXR0JmUE1mRml2bEor
            Nk54bVVBcUVRcUtDSFRPYXNyblQ1UXcKLS0tIGUvaG9ISEEzSzBRY2xOY1NTTWhX
            RHUzOUVJcFVTMlNRdFZPdWd4MkxzeHcKUJl1I1FEzVU2xZI2OA9Dge2K6jqlCf3R
            /uLVFixVleI+1n5ZdhfQG3p2Vt+c2vksfIw6/iygmKEoSYxnG3Hqxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-01T19:50:05Z"
    mac: ENC[AES256_GCM,data:pd27tWiFqJYyC56jvskIiEHm/6xQiZ8XkIacFYJDsLsb+QYJ4Ct05Tg2wDo9bMziVCQy/mJLbdnencs0JX7D0fVrweNVQLWJ9J9DKlzgqhK1NVn8CBlgV660aamQ2xI4h9S4K4c6kzXsIFXu24XhPFaE+GXJ0nlZ1E1BEExcGpE=,iv:I+8wEXaHfqL3FBPkAa41Q53mvafTxU+i4/A9vfAhC3w=,tag:3oGCN/3UTsKy3w/boJhjMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
