# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:sKnE72rLOsIZs+4WDvDt8/yYOixgjmqRuQ==,iv:Ty3e+vG2nSApMggkLQjtQOiWovUpweTqXBnIILMoDbw=,tag:BWKKz66UOSuE+GoQ/BB+yQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:3LaeQUzB+EC8Lyj9gUGkOrBDYi0U+SuzeATGJecfR3+hK0+1/g==,iv:u8R0NmFxyIXbyXgd187ehaQEh1bARyrQOR2tGqww8A0=,tag:mcvWBbssBFCfZgZm+8o7ig==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:K6dtMBwhhL8AnXBqEH/xhZLFZg==,iv:RbvPYCUq39Ham3fAWCgF6m2gaO1SJHcKXbxkcTSYZBM=,tag:XJZtINaiz5ZilRuYXqjRIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zcvg7j382g4lsdaq46lhapjg5eg6guuf4vx9ce0zy2p7qngzqd6spqnmgp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOKzBZK2pLYkI1a2VXMGk5
            VHJkWlp5Tmp2RGU3Z0w0cFcwSE5FUE56OVVJClVWUFdxRmE0NEI0Z1VyS2orZ1J2
            czRZNjF4M093ejJZWFl1K0VWSXI3NHMKLS0tIFFEUlhhempMNS9IY0svNERIL01h
            YTB2ZTN1TTBnWHBacWFCR2ZsRUVxYncKMf2d8VlYbF+L11YCC1+Z7hG0U+t0fKjf
            Wxsh0XLBbSsfHq2XnmP8pnck+vG5TAgNkmdbzgkedCT+Cuuc8NbYZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-01T17:05:48Z"
    mac: ENC[AES256_GCM,data:EzjWog7lRZTC5lRLKA25ziN9wl7RZGY+0ecIBpFFf3Kpb/WwuVRNIX4O16NM5y3BnZYqx/y5wBj8eC/tDdhw+q6YQ3lDZEBsuyiWA23Z/WMVFXvOYjuIOpClQEpUJKPK6Pfwy4vL0zdyklh0gMv08tFmsgZMioTuvIQnw0x89hA=,iv:+VmUHxxk0DeqaAGjA7VxNQ+enbW8kH6MgQKxAfp3Rl4=,tag:HnccEgnv1wHxdWnRpsMHiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
