# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:MCxWz/9hvh/zP2uiDXO1UG/2pwENjC72mA==,iv:8jf13PwQ+WRcT+3BrUZiid29pM59R2fqlVQxFTWnStI=,tag:916VD5Yik9UX0qpx6LvkNw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:fhTkkvVK+n9jA1kkQKDZf4NAWCu69gEfy34lwD2kYOz18LLvCg==,iv:6RxB82zCyiWq5Zs7NYd3lypkGC8IF7ksqvUyF9FFKvE=,tag:nXqGgvOw/luu0T33P0kknQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:wU8MQA47ByqDmtI+aSxL,iv:eOv52cckX+Z2t2oGvKLeeJg4zFtx0ASSRBIsfd25yaE=,tag:mgIRAxiPkNuEAyewN4eaUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zcvg7j382g4lsdaq46lhapjg5eg6guuf4vx9ce0zy2p7qngzqd6spqnmgp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBR2NsMStFRC9IZ3VOTk4v
            UDhrZytsdmZmUTZHWWJ6NjJlUStEWXlHa0E0CktONXNpc2NqWUtNOGVYSnlYbGdz
            NlhWTEYxOXFhWlR3WnpBYzdieWVoVmcKLS0tIEtWZ3pnU0RzRGQxZFY4UDdpMEdx
            WVp5WXdiRVVoR2J2VnM4RDdwMFBxemsKrM8QU7TeWWE/ysoRSv2ileBKBSbME79A
            XpSpullC+xNRVNgBXhRKbRtYNhRT7e1lEAeaSmSIYOX4VmiwgyDraA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-02T18:54:35Z"
    mac: ENC[AES256_GCM,data:o6tD9N16TqxIQxz9zxc2E7SSvVAjvRBbBLRKtquPPDWC8IQzDaYehHkM/sUnV7p1pO6CfNhhnVeJ1qnilqSE/lTZKriburSwlPsSYcOEeJqpp+oLt2jjXiirmVTtJJkZKUokUkCVS74lv1yC2PX+yM2F4AJ4gyzurvmHsqhqAJw=,iv:8izZJP62IVfN2tSJ4fwUWsl9aVXgREUEAkFGzvAcc9I=,tag:EfiAfXkoPyzUOkJU/fOCdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
