---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netmaker
  namespace: nm
spec:
  interval: 5m
  chart:
    spec:
      chart: netmaker
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: netmaker-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
#  values:
