---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netmaker
  namespace: nm
spec:
  interval: 5m
  chart:
    spec:
      chart: netmaker
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: netmaker-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    baseDomain: "netmaker.${SECRET_DOMAIN}"
    postgresql-ha:
      postgresql:
        database: "netmaker"
        username: "netmaker"
        password: "netmaker"
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
        hajimari.io/enable: "true"
        hajimari.io/icon: "weather-sunset"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        #traefik.ingress.kubernetes.io/router.middlewares: default-basicauth@kubernetescrd
      hosts:
        - host: "netmaker.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "netmaker.${SECRET_DOMAIN}"
          secretName: "netmaker-tls"
