# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:MoD+iMlgaUrvDUx9BLZx9Ra7QZG5Gii3YQ==,iv:jE+K61TGJzkK6sL290g6vZxhoAbKzinDw5Fu4XxrmqU=,tag:i6TSmkoVBxIwPnxTrcDhSQ==,type:str]
    api-key: ENC[AES256_GCM,data:pOsLckjKnoB1DbmjBP0k+LlXKl4a+C6dXAQxaUaUsqFIUd108g==,iv:SsHJ37vd5Qo8PSPEkgY8L3sk7DX6o68iiF5Kc2IyiJI=,tag:VTQZ7QqyYtclZw+YGDUHxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zcvg7j382g4lsdaq46lhapjg5eg6guuf4vx9ce0zy2p7qngzqd6spqnmgp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaEdvRVpEalNHMHI2N2xs
            d3FuakNlVkY4OGl0MUNlcEk5TU8wQThkOFYwClRJVW9ZOHdmSDRGeEdhM0ZOcmQ1
            bElXMW5Vc1V0UDJ1RERQWjZoMmdSV2cKLS0tIFI3Q2tTS2dUeUhQWm12THZTTTc2
            WG1FeW5Oc0JNMk1uQ0g4TFJHNHNUV3MKN1O70EJi0iRugzSIMMUP1vb/rLeRtCEZ
            uQR7W/S76ThjPPZ6uDnVHjr4HC/xO71/PTJm1Qgr/7rKYXFEEmRGGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-01T19:33:22Z"
    mac: ENC[AES256_GCM,data:lKyAL6FIxlnPkDFsMuyd/x8dZlsM7uzqAhVwZPJUJH8UlTQyyYAdqpjDEkJQHYmU5/rpAEOX8QJ6+X3QibdclVXGGJds0jKdO5JAAv+C69wIr+X0wsqUVr/W+UoENp29NPaIQKyriv7xj+sdZcNIZHlsdJyXXDXtMkdwI3gcfFs=,iv:XOYLVgAHj5u8nYI5vTQ586wBbuIPjpMus4AHjE5RInI=,tag:PRahjVyDnc/zUJ2q9A1ghA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
