# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:8cnWnjxEtyZw4SUkg15l7Qya9Zk3dOxqrT1yzA8dtsNw2tz9lXWPEA==,iv:HwSWepnv9JUI78hEAmwFBXfsyfpXaIUAlVuM6mX+uAI=,tag:7qNghwb06OAdaah4k/Rj9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zcvg7j382g4lsdaq46lhapjg5eg6guuf4vx9ce0zy2p7qngzqd6spqnmgp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNnhVVzUvRjNTOXpobGRH
            cFVNdjkxU3ZNWUhUUW5semNDNTFOeEkrU1g0CjBxNmlvNUxBQXB3MkVEQTV3Z3lN
            RnRlcEQ3T0E4SGhiNjU1QmFsNm9rcEUKLS0tIEtZaUI4T0h3UWxMRjlGekpEQjFt
            ODdMdE5pV2tRa2UwV3czTnM4RWp2aFkKLlun/sj4CvodlOGU9goCu4ENNH1dVfnt
            ztjb2yEKrWBB0SRc7z8uTc5tTppv18Y9irfzfJZeqCYYu51UjyXg9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-02T15:20:22Z"
    mac: ENC[AES256_GCM,data:9FprGFyaLlHyENOy24AwWkf6uMXKAojVMPQIGMetDwsyGQaaBb2p0P+UYfig0f+Un1720BUAjJRVdqacxarsqKBrzBlhBjIouIOfH2411kQRfInLREguMSE01HhNldVKCJI5uk164lkKRSLnfwjoGaeGqEuBIi+KQ50YuaG/1/Q=,iv:tynuYpbGyH+j9+X7uLyOlJH3WDRshLXmaiU1eZSQ2wo=,tag:MU8UmxhQKndNcPv/zO+5hQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
