# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:H5CTr7W3y4kUK1RyWjvngar+ASwmXTRyerzB8nX1MWBfWYKkVfoIGw==,iv:2Q/n8Tulia3uUXUn/MgDag+tc13Hf7actIXBVaXQ1cQ=,tag:rAdErJ2s/P4L68DxhybCzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zcvg7j382g4lsdaq46lhapjg5eg6guuf4vx9ce0zy2p7qngzqd6spqnmgp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMWc5WGhGUnYxUGFqSDhJ
            dm01eUtJMXJPQWoyWlBwQ0pBRmE1YnF2dWtFCmppQ2dUazUxNURFWkp0eUdvZXBt
            MHVENnlmMXdRUCt0K0NRZis4dDNnY2sKLS0tIHYvV3BHVlJXZmpHUXlFMXpNaFdF
            NFFpSzJSUkMyZXpWSXdoZHBjRkthNlkK51+WAXfmCn41ZjAQcvCkVbu3Ps7eAdey
            YfCDtw+bpg7YbjKPoY8fO7TblruIlNfq1NKeWjC7SFFiJ450CSUfUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-01T19:50:05Z"
    mac: ENC[AES256_GCM,data:pybUJoXTVLezF1H6UHjz1nAgBcA110UFPaWdHiyKL6+CwhtI/Bp1v371Y+EQiCPB00IlIQVFUoxZNpXygwl8g2qxMeWFsao06WJvg2VVB/TGIzl9WmIVqOas5gZTgUZ9+A0UShs5Vx7eJ3qQJFHrR4j1to6YMHi/4D/z7HcvNkg=,iv:T2vFP9R5gYOxE1PvCioIWXN2xdhHsH/a5GjKiq40u9Y=,tag:cyTVVhK5yom3CdNKXRH+vA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
