# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:7gtOjRX60vEfPFwsUz3fYI6sPasTf0CPxkj9fq2BfGeHg71Y/Q==,iv:UdowL2yMlnz4PeK+Ji7J9RfuSAI/QeUkJbNhY0wNF14=,tag:q0rOwr/N1A/QAhtSF4l1OA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zcvg7j382g4lsdaq46lhapjg5eg6guuf4vx9ce0zy2p7qngzqd6spqnmgp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYlVvT0FJVEJUTzZyWkx4
            SlQwMlIwOTlTVDQrNGhmTkNYREduTC92cVdRCm1Rb3FNbll0K1VwOG9nSCsxZTVT
            V09weUhNcjM5Mk53TTJEb1lpOUtDUG8KLS0tIFE0RGdZS0wzWGdscWhyRmlUd1FR
            cnVwa2dJT1ExcWdiZ29Rem53QXJ4VDAKx39A5bxXLFOx++W0Iy52G4hw5tBERQdB
            nKDC8ezjCyxM0l6VyaeF9KfVLZgPCtILxNznaDyivmfPYAixDaKQig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-01T19:33:22Z"
    mac: ENC[AES256_GCM,data:jWzug4nIZ5tKpvmy8TnHxHlMyABVJwzgw68A4d2g3z0vrnYw8jiXcIkYkC0qhvfGQQyWNVgTO2ftSgnkQ/WqHWUMRxacLMsWY3rwee8hC3JvYQOjbq1lUaiEs/N1EAuaKrfcTfwgYvvzdVFUDwaYGGU/1u2zK3ogqpJzujaGCYI=,iv:5A3MCVVQY6GnnkJ6iABUHzndx9qTQePLGetF5m4/Ezk=,tag:RelHssuywWjkJ3VcK4N1kg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
