# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:bEXVebftJTKvQyqgxPoFUDgZgZRFNnzwOtEzACy4yXzikr/5zw==,iv:AJEybgqYIeRiSH65tGGFxGaxf75AK7v5zId0JbVQ1KU=,tag:NvYpWz3wFZgVgvcbtM/nXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zcvg7j382g4lsdaq46lhapjg5eg6guuf4vx9ce0zy2p7qngzqd6spqnmgp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQUxwWDFNcWJlV0ZPMHdZ
            bFlZRnJsd1J0TDNnL3V2T2c1V0o3aHd3M0JzCmh5SDJYdllkaDRpWG44SmtNNmcw
            STd3TjJzVk9MbHh0ellheVZVMU9lb1EKLS0tIE93UnVTbENCbXFlRXpiMUZmYm10
            T3BPSGtiU1hZdUdrbGtQb0dGOGJlak0K3ah6AeGsmsVvIfQ4ONdQcg9LJYPJH+2R
            SMf21AerweneOD44uCq0lUmYIQxrDuLj1yrY34Jg1j1IxZj9wmrx/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-02T18:54:35Z"
    mac: ENC[AES256_GCM,data:wKxiBMA6RHdv9DbfCtbwqPIn+xCJF9t5uAAVD/JqYDVLyRVTB6l99dmMeYiaH3fosZ4WCxGf/dkwbf0ZWZg1p+S1TPoJoWpnIe5eo2o4o6EvolHHSnoIyq6pevztEGAlCefSKMofUrgdm6V8TrLr9AQZiW1DTfv7suaTjb1QMpc=,iv:DyzqQXeILFj5oyuNs6JE9aL+1emzd3308UvrEl2L6dE=,tag:iwqt3ojZElGxBdzb4NWo8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
