# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:z+yq/7+jeDBAKCFuggsb+2KU/cRRN/FsZMdAKW1orvwMJKVjYA==,iv:miHKaXYu2h3oWIfUi06B2NPM/4SvjYprw7EOSrDcsQs=,tag:jo94ciFIRCkbp/nQL2PWdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zcvg7j382g4lsdaq46lhapjg5eg6guuf4vx9ce0zy2p7qngzqd6spqnmgp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aXVrcS9lSW1LMjVwUzJJ
            VkkwZVdJcXRUWTJKRGI0UWxyNWcxM2U2bnlJCnRNUEcxS3J2S0hiaWNUYWhzbVpm
            eXZJa2ltVEJUVHhEWmsyZlpxZTFWUFkKLS0tIHJ1a3J3bjRacVk5bUdjbEkvT2I5
            VHRaNzUrNUFjaEVqcGQ4cDJBTlVUSE0KpuRF/M/YTguydqj3nM/Ws6mM6v9lf5Z5
            C3iFhGpTqLha0KqzQ8hrWg1rkuInuBI05qkrUXz2fb8nwQRCVHJ0Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-25T18:27:24Z"
    mac: ENC[AES256_GCM,data:Ae5HVFIaGwNcFAaJvCFrF4QhufMOKNdJ5jeDEXa1P0aT7fXTwHogpXPFW1pqNpDKZdg7vhO1BroNfidFktArNCuOmL8EJmqdCX445R/G1Db4Me+AWaoPXOsIg7ibAoqc3Si0ppk6Wy1sK/a1QucNMvFnEdK9RzGX8LhBSx28OiU=,iv:lcC+EHJud2F3eV3Twn3EM27ZzX/aTYfpWmzOCI4LtqU=,tag:OzNEVfxoaRPu/HT3IVNy6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
