# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:qR7tESE4hDAiMGJo9RkuuwLYPRk7kIy5U7PuInzwOEBoi+yv7A==,iv:Zpsewon2OOKELe64SEOP/IqDeAwwSAF7rTUElUguyRU=,tag:R+xmbvpvSCPX+qijDP3bGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zcvg7j382g4lsdaq46lhapjg5eg6guuf4vx9ce0zy2p7qngzqd6spqnmgp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYTBmVE03NzJzL0QySEJz
            S2IrelN3WWw2b2ZLVFJ0S3R6YUw0MEVIMXc4CmhZQUgvUDJBQ2FINXUzWk8yMy96
            TlpTcjdjNG5nZzNBQ25IcGxHWTdXUGcKLS0tIHplSlFaNFRUVkFVNmRrNVpMazE2
            dUllWTYrQ3FBaHpQY2Y5RUpZZ1JLTDgK/9Dkxjkt68srARw0pQ6EMyYzvv8zacOG
            3AUNuE2vehjz7SNejb6mcXyCQzqdX84LjkcVQXaj3Epf3xar3mN52w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-02T15:20:22Z"
    mac: ENC[AES256_GCM,data:Bc3yEBHPKXleEar9w3KPhq3ucz+JEdp8O6PtMQKytkRkiIXn9KZJYUGT5JScKVjiQB9ku4r4AHDly1iu/tknbFaF2fmtyd2t7kSfy5bkOfvP1NHsvcU4I8oRDwwfIS3AzlXculkbxxLosKldp8cp0dKKfTMIvusAuQQa0cC/Vmw=,iv:+i/ZGFF2F6Rg+oBH0n3uUQMe8dmZ08/P1QOmqhIjU6o=,tag:L14iL+9dZp0M12GZ1KuS4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
